name: Release CD

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release_linux:
    name: Release - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@4
        with:
          distribution: 'semeru'
          java-version: '21'
          cache: 'maven'
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile project
        run: mvn -B package -Pnative,portable
      - name: Upload jars to release
        uses: svenstaro/upload-release-action@2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          file_glob: true
      - name: Upload manpage to release
        uses: svenstaro/upload-release-action@2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debian-control-linter.1
          file_glob: true
      - name: Upload native executable to release
        uses: svenstaro/upload-release-action@2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debian-control-linter
          draft: true
          file_glob: true