name: Release CD (automatic)
# Uploads the jar files and the manpage to any created release.
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release_linux:
    name: Release - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'semeru'
          java-version: '21'
          cache: 'maven'
      - name: Compile project
        run: mvn -B package -Pportable --file pom.xml
      - name: Upload jars to release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          file_glob: true
      - name: Upload manpage to release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debian-control-linter.1
          file_glob: true