name: Release CD
# Compiles the native executable without needing a release. The executable has to be uploaded manually.
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: The release version to build
        required: true
        type: string

permissions:
  contents: write

jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run release tests
        run: bash src/test/release_tests.java '{{ inputs.release_version }}'

  release_linux:
    name: Release - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'semeru'
          java-version: '21'
          cache: 'maven'
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile project
        run: mvn -B package -Pnative --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-control-linter
          path: ./target/debian-control-linter